%% Date 2020.6.2
%% Author: Qi Yang (Any question, please contact:yang_littleqi@sjtu.edu.cn)
%% Affiliation: Shanghai Jiao Tong University
%% If you use our code, please cite our paper: Point Cloud Distortion Quantification based on Potential Energy for Human and Machine Perception
%% https://arxiv.org/abs/2103.02850
%% ****************************************************************************************************************
T=0.001;
%% resampling version, generated by demo_fast_make.m
name_resample=('redandblack10000_4.ply');
%% reference point cloud
pc_resample=pcread(name_resample);       
name_r=('redandblack.ply'); 
%% distorted point cloud
pc_ori=pcread(name_r);
name_d=('redandblack_0_0.ply');            
pc_dis=pcread(name_d);

score = MPED_score(pc_ori,pc_dis,pc_resample,5,'2-norm','RGB',T);

