%% Date 2023.5.19
%% Author: Qi Yang, Yujie Zhang (Any question, please contact:yang_littleqi@sjtu.edu.cn or yujie19981026@sjtu.edu.cn)
%% Affiliation: Shanghai Jiao Tong University
%% If you use our code, please cite our paper: MPED: Quantifying point cloud distortion based on multiscale potential energy discrepancy
%% https://ieeexplore.ieee.org/abstract/document/9917335/ 
%% ***************************************************************************************************************
%% resampling version, generated by demo_fast_make.m
clear
name_resample=('redandblack10000_4.ply');
%% reference point cloud
pc_resample=pcread(name_resample);       
name_r=('redandblack.ply'); 
%% distorted point cloud
pc_ori=pcread(name_r);
name_d=('redandblack_0_0.ply');            
pc_dis=pcread(name_d);

SPED_5 = SPED_score(pc_ori,pc_dis,pc_resample,5,'2-norm','RGB');

SPED_10 = SPED_score(pc_ori,pc_dis,pc_resample,10,'2-norm','RGB');

MPED = (SPED_5 + SPED_10)/2;